### ISSUE TITLE
Error: Cannot find module 'basisjs-tools-instrumenter' from 'рабочая папка'

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [basisjs/basisjs-tools#24]
Поставил пакет глобально
> npm install -g basisjs-tools

Попытался запустить сервер
> basis server

выдало:
> Error: Cannot find module 'basisjs-tools-instrumenter' from 'рабочая папка'

Поставил пакет basisjs-tools-instrumenter глобально и ошибка повторилась.

Решил установкой basisjs-tools-instrumenter локально.

**Comment by smelukov** [comment]
basisjs-tools-instrumenter должен быть прописан как зависимость в package.json, тогда достаточно будет просто сделать npm install в рабочкй папке

**Comment by lahmatiy** [comment]
Наверное проблема в том, что инструменты не ищут плагины глобально. Не знаю насколько это проблема, так как для каждого проекта специфичен набор плагинов и версия. Была идея чтобы и basisjs-tools ставился глобально, но при запуске в папке, где есть в зависимостях basisjs-tools использовались инструменты самого проекта (его версия). Но это немного в сторону...
